[features]
seeds = true
skip-lint = false

[programs.localnet]
swap_program = "58YS7hZ1Sc1zPetRioEmA3R2zumu2kMTAXkKPs6RFpWQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/joesol/.config/solana/id.json"

[scripts]
upload-json = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/upload-json.test.ts"
create-assets = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-assets.test.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/main.test.ts"