[features]
seeds = true
skip-lint = false

[programs.localnet]
swap_program = "25oCdYAQKYPUj17S678SyNKtjg1FeuoJtJgZXCKJPdky"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/joesol/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/main.test.ts"
create-assets = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/create-assets.test.ts"